# Generated by Django 4.1.4 on 2023-04-12 20:23

import bookreview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValueBookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[bookreview.models.validate_rating])),
                ('review', models.CharField(max_length=100)),
                ('spoiler', models.BooleanField(default=False)),
            ],
        ),
    ]
