# Generated by Django 4.1.4 on 2023-05-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='shop.catalogproduct'),
            preserve_default=False,
        ),
    ]
