# Generated by Django 4.1.4 on 2023-05-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=0, upload_to='shop/'),
            preserve_default=False,
        ),
    ]
