# Generated by Django 4.1.4 on 2023-05-18 17:47

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to=shop.models.product_image_directory_path_path),
        ),
    ]
