# Generated by Django 4.1.4 on 2023-05-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
    ]
