# Generated by Django 4.1.4 on 2023-05-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ShopUser',
        ),
    ]
