# Generated by Django 4.1.4 on 2023-05-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_catalogproduct_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogproduct',
            name='slug',
        ),
    ]
