# Generated by Django 4.1.4 on 2023-05-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
