# Generated by Django 4.1.4 on 2023-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_order_total_cost_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
